### ISSUE TITLE
Bar is hiding in case of iPhone X 

### ISSUE THREAD

**Issue by Nishadarora** [furqanmk/NotificationBar#2]
<img width="325" alt="screen shot 2018-05-10 at 3 55 33 pm" src="https://user-images.githubusercontent.com/14192988/39865507-bde720d2-546a-11e8-8f10-1cfb46952318.png">

**Comment by maroofkay** [comment]
Do try it now!

**Comment by Nishadarora** [comment]
Yup everything now looks good
