### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [furqanmk/NotificationBar#4]
Hi @furqanmk  I am a graphic designer and i want to contribute her by proposing a logo design for your project which I already have an idea and needs your permission first before i start designing. Ill be going it as a gift for free to your good project. Thanks and best regards! - Tobaloidee

**Comment by furqanmk** [comment]
Hey Tobaloidee,

Thanks for considering my project! I would be really glad if you design a logo 😊Please go ahead.

Regards,
Furqan Khan.
________________________________

**Comment by Tobaloidee** [comment]
Okay Sir! Ill start my design and show you here as soon as i am done.. thanks for the permission.. :)

**Comment by Tobaloidee** [comment]
Here's what i came up with, design simply based on the notification bar. Colors used was from the sample gif on the readme. Still open for your suggestions or modification Sir.

![pres-04](https://user-images.githubusercontent.com/36028424/41820989-bae56392-780c-11e8-9c60-58556bcde238.png)

**Comment by furqanmk** [comment]
That's really really good! I personally like the one with primary green with yellow bar and I think you picked the same as well.

**Comment by Tobaloidee** [comment]
I based it from the colors in the readme.. :) can i make a Pull request and upload the files and update the readme?

**Comment by furqanmk** [comment]
Cool! Sure, go ahead.

**Comment by Tobaloidee** [comment]
Here's the PR #5 Sir, Thanks and best regards! -Tobaloidee

**Comment by Tobaloidee** [comment]
I will close this issue now Sir, Thanks for accepting and using my contribution..Best regards!
