### ISSUE TITLE
iPhone X loader is not centered

### ISSUE THREAD

**Issue by mrazam110** [furqanmk/NotificationBar#7]
Device: iPhone X Simulator
Branch: master
Last Commit: 3b0168e 

I think the activity indicator should be centered with UILabel

![simulator screen shot - iphone x - 2018-10-19 at 12 51 15](https://user-images.githubusercontent.com/5674070/47205329-027ff080-d39f-11e8-8927-98050a0236f8.png)

**Comment by maroofkay** [comment]
I think it is centred. But I guess it should be aligned with the label, instead of being centred.

**Comment by maroofkay** [comment]
@furqanmk, your say? Should we align it with the label?

**Comment by furqanmk** [comment]
Yes. I agree @MaroofKhan.
